# Generated by Django 5.2.17 on 2026-09-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='live_chat_enabled',
            field=models.BooleanField(default=False, verbose_name='Live chat approved'),
        ),
    ]
