# Generated by Django 5.2.17 on 2026-09-12 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='context_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='context_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chat',
            name='locality',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='message',
            name='citations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='context_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='kind',
            field=models.CharField(default='answer', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='lookup_status',
            field=models.CharField(default='not_requested', max_length=24),
        ),
        migrations.AddField(
            model_name='message',
            name='paragraphs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ActiveNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_note_id', models.UUIDField()),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_notes', to='chats.chat')),
                ('source_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.personalnote')),
            ],
            options={
                'ordering': ['attached_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('chat', 'original_note_id'), name='unique_active_chat_note')],
            },
        ),
        migrations.CreateModel(
            name='ChatTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_request_id', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=12)),
                ('content', models.TextField(blank=True)),
                ('note_copies', models.JSONField(blank=True, default=list)),
                ('context_version', models.PositiveIntegerField()),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('error_status', models.PositiveSmallIntegerField(default=502)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='chats.chat')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('chat', 'client_request_id'), name='unique_chat_reservation'), models.UniqueConstraint(condition=models.Q(('status', 'processing')), fields=('chat',), name='one_processing_turn_per_chat')],
            },
        ),
    ]
