# Generated by Django 5.2.17 on 2026-09-12 18:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def preserve_usage(apps, schema_editor):
    alias = schema_editor.connection.alias
    gate = apps.get_model("chats", "LiveUsageGate")
    usage = apps.get_model("chats", "LiveUsage")
    turns = apps.get_model("chats", "ChatTurn")
    gate.objects.using(alias).get_or_create(pk=1)
    for turn in turns.objects.using(alias).select_related("chat").iterator():
        record = usage.objects.using(alias).create(
            owner_id=turn.chat.owner_id,
            created_at=turn.created_at,
            expires_at=turn.expires_at,
            finished_at=None if turn.status == "processing" else turn.created_at,
        )
        turns.objects.using(alias).filter(pk=turn.pk).update(usage_id=record.pk)


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0002_chat_context_started_at_chat_context_version_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveUsageGate",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="LiveUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chatturn",
            name="usage",
            field=models.OneToOneField(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chats.liveusage",
            ),
        ),
        migrations.AddIndex(
            model_name="liveusage",
            index=models.Index(
                fields=["owner", "created_at"], name="chats_liveu_owner_i_903cb0_idx"
            ),
        ),
        migrations.RunPython(preserve_usage, migrations.RunPython.noop),
    ]
