# Generated by Django 5.2.17 on 2026-09-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_liveusagegate_liveusage_chatturn_usage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='urgent_help',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
