# Generated by Django 5.2.17 on 2026-09-13 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_message_urgent_help'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='saved_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notes.personalnote'),
        ),
    ]
